### ISSUE TITLE
Creating a local environment using environment file with pip dependencies fails with errors

### ISSUE THREAD

**Issue by jasonboukheir** [mamba-org/micromamba-releases#39]
Here is my `environment.yml` file:

```yml
name:
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python >= 3.8, <3.9
  - pytorch
  - pytorch-cuda=11.8
  - torchvision
  - pip
  - pip:
      - ultralytics
      - pillow
      - numpy
      - pandas
      - git+https://github.com/openai/CLIP.git
```

When running the following command:

```sh
micromamba env create -f environment.yml -p ./.conda
```

it fails with

> Installing pip packages: ultralytics, pillow, numpy, pandas, git+https://github.com/openai/CLIP.git
> critical libmamba Cannot activate, prefix does not exist at: '{ SNIP }\micromambaenv\envs\.conda'
> critical libmamba pip failed to install packages

It seems to be trying to find an environment called `.conda` instead of using the environment I have locally in my project.

I'm using micromamba version 1.5.6 on windows.
