### ISSUE TITLE
micromamba 1.5.10 fails to create environments in parallel when cache has been cleaned with `-f` before

### ISSUE THREAD

**Issue by b-morgenthaler** [mamba-org/micromamba-releases#64]
Hi,

**Context**
We are using [micromamba 1.5.10](https://github.com/mamba-org/micromamba-releases/releases/tag/1.5.10-0) in our Gitlab CI pipeline. The Gitlab runner is an Ubuntu 22.04 LTS VM (shell executor). The pipeline has several stages: one of the first ones is taking care of creating the environments - one environment per job. At the end, the .post stage is taking care of cleaning the micromamba cache (the created environments are removed already). There is no configuration file existing - so all defaults unless given by the command line options.

**Error**
I noticed that micromamba (libmamba) fails, when the jobs (hence the environments) are created in parallel with this error message (similar errors for each job's environment):

```bash
Executing "step_script" stage of the job script
$ ${MICROMAMBA} create --no-rc -y -c conda-forge --no-pyc --strict-channel-priority --allow-uninstall -f ${CONDA_LOCK_FILE} -n ${CONDA_NAME_1}
Empty environment created at prefix: /home/gitlab-runner/micromamba/envs/unique_name_1
Transaction
  Prefix: /home/gitlab-runner/micromamba/envs/unique_name_1
  No specs added or removed.
  Package                                             Version  Build               Channel                                                             Size
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  [a lot of packages to be installed]
  Summary:
  Install: 232 packages
  Total download: 0 B
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Transaction starting
error    libmamba Error opening for reading "/home/gitlab-runner/micromamba/pkgs/[package].conda": No such file or directory
[package].conda tarball has incorrect checksum
error    libmamba File not valid: SHA256 sum doesn't match expectation "/home/gitlab-runner/micromamba/pkgs/[package].conda"
    Expected: 68d3bbfe418dda8805b7af1e933b45a2ec4064dae53a281201418cad79578b45
    Actual: e3b0c44298fc1c149afbf4c8996fb924ae41e4649b934ca495991b7852b855
    
warning  libmamba '/home/gitlab-runner/micromamba/pkgs/[package].conda' validation failed
critical libmamba Found incorrect download: [package name] Aborting
```

**Findings**
- The package is not the problem because:
  - when the jobs are not run in parallel, all environments are created successfully
  - when I use a different conda lock file, it's a different package that fails with similar error message (presumably the first package to be installed)
-  When I remove the `-r` from the `micromamba clean` command in the .post stage, it seems to work also in parallel.

Here's a minimal gist of the pipeline for better understanding the use case:

```yaml
variables:
  MICROMAMBA_PATH: ${CI_PROJECT_DIR}/micromamba/linux/bin
  MICROMAMBA: ${MICROMAMBA_PATH}/micromamba
  MAMBA_ROOT_PREFIX: /home/gitlab-runner/micromamba

stages:
  - qa

env_1
  variables:
  stage: qa
  before_script:
    - ${MICROMAMBA} create --no-rc -y -c conda-forge --no-pyc --strict-channel-priority --allow-uninstall -f ${CONDA_LOCK_FILE} -n ${CONDA_NAME_1}
  script:
    - echo "do some things inside the environment"
  after_script:
    - ${MICROMAMBA} -n ${CONDA_NAME_1} --no-rc -y env remove || true

env_2
  variables:
  stage: qa
  before_script:
    - ${MICROMAMBA} create --no-rc -y -c conda-forge --no-pyc --strict-channel-priority --allow-uninstall -f ${CONDA_LOCK_FILE} -n ${CONDA_NAME_2}
  script:
    - echo "do some things inside the environment"
  after_script:
    - ${MICROMAMBA} -n ${CONDA_NAME_2} --no-rc -y env remove || true

env_3
  variables:
  stage: qa
  before_script:
    - ${MICROMAMBA} create --no-rc -y -c conda-forge --no-pyc --strict-channel-priority --allow-uninstall -f ${CONDA_LOCK_FILE} -n ${CONDA_NAME_3}
  script:
    - echo "do some things inside the environment"
  after_script:
    - ${MICROMAMBA} -n ${CONDA_NAME_3} --no-rc -y env remove || true

clean_environment:
  stage: .post
  script:
    - ${MICROMAMBA} clean --all -r -y || true
  when: always
```
